"""Vision utilities and adapters for RestaurIA."""

from services.vision.calibration import (
    CalibrationFile,
    TableCalibration,
    build_table_calibration,
    calculate_homography,
    extract_roi_view,
    load_calibrations,
    order_quadrilateral_points,
    save_calibrations,
    target_rectangle_points,
    warp_table_view,
)
from services.vision.capture import CaptureConfig, FramePacket, OpenCVCaptureAdapter
from services.vision.classical import (
    ClassicalTableSignalExtractor,
    ClassicalVisionConfig,
    SobelGradients,
    TableSurfaceSignal,
    gaussian_blur,
    histogram_equalization,
    sobel_gradients,
    to_grayscale_uint8,
)
from services.vision.explainability import (
    PatchImportanceMap,
    PatchOcclusionConfig,
    PatchScore,
    normalize_importance_heatmap,
    occlusion_sensitivity,
)
from services.vision.geometry import (
    BoundingBox,
    FrameResolution,
    PolygonRescaler,
    PolygonScaleReport,
    ScoredDetection,
    ZoneAssignment,
    denormalize_polygon,
    normalize_polygon,
    same_aspect_ratio,
)
from services.vision.hybrid_inference import (
    DetectionProvider,
    HybridInference,
    HybridInferenceConfig,
    HybridInferenceMode,
    HybridInferenceResult,
)
from services.vision.kalman import (
    BoundingBoxKalmanSmoother,
    ConstantVelocityKalmanFilter,
    Kalman2DConfig,
    KalmanEstimate,
)
from services.vision.lk_tracker import (
    LKTrack,
    LKTracker,
    LKTrackerConfig,
    PointBoxAggregationConfig,
    points_to_bounding_box,
    tracks_to_detections,
)
from services.vision.motion import MotionDecision, MotionGate, MotionGateConfig, detect_motion
from services.vision.observation_adapter import (
    DetectionToObservationAdapter,
    DetectionToObservationConfig,
    TableZone,
    TemporalCountSmoother,
)
from services.vision.realtime import (
    FrameSkippingConfig,
    FrameSkippingPolicy,
    LatestItemBuffer,
)

__all__ = [
    "BoundingBox",
    "BoundingBoxKalmanSmoother",
    "CalibrationFile",
    "CaptureConfig",
    "ClassicalTableSignalExtractor",
    "ClassicalVisionConfig",
    "ConstantVelocityKalmanFilter",
    "DetectionToObservationAdapter",
    "DetectionToObservationConfig",
    "DetectionProvider",
    "FramePacket",
    "FrameResolution",
    "FrameSkippingConfig",
    "FrameSkippingPolicy",
    "HybridInference",
    "HybridInferenceConfig",
    "HybridInferenceMode",
    "HybridInferenceResult",
    "Kalman2DConfig",
    "KalmanEstimate",
    "LatestItemBuffer",
    "LKTrack",
    "LKTracker",
    "LKTrackerConfig",
    "MotionDecision",
    "MotionGate",
    "MotionGateConfig",
    "OpenCVCaptureAdapter",
    "PatchImportanceMap",
    "PatchOcclusionConfig",
    "PatchScore",
    "PointBoxAggregationConfig",
    "PolygonRescaler",
    "PolygonScaleReport",
    "ScoredDetection",
    "SobelGradients",
    "TableZone",
    "TableCalibration",
    "TableSurfaceSignal",
    "TemporalCountSmoother",
    "ZoneAssignment",
    "build_table_calibration",
    "calculate_homography",
    "denormalize_polygon",
    "detect_motion",
    "extract_roi_view",
    "gaussian_blur",
    "histogram_equalization",
    "load_calibrations",
    "normalize_polygon",
    "normalize_importance_heatmap",
    "occlusion_sensitivity",
    "order_quadrilateral_points",
    "points_to_bounding_box",
    "save_calibrations",
    "same_aspect_ratio",
    "target_rectangle_points",
    "sobel_gradients",
    "to_grayscale_uint8",
    "tracks_to_detections",
    "warp_table_view",
]
